services:
  zeek:
    image: zeek/zeek:lts
    container_name: zeek-monitor
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - /sec/zeek/logs:/usr/local/zeek/logs
      - /sec/zeek/config:/usr/local/zeek/share/zeek/site
    env_file:
      - .env
    command: >
      sh -c "
      sed -i 's/interface=.*/interface=\${ZEEK_INTERFACE}/' /usr/local/zeek/etc/node.cfg &&
      /usr/local/zeek/bin/zeekctl deploy &&
      tail -f /dev/null
      "
