services:
  ai-middle:
    build: .
    restart: unless-stopped
    network_mode: "host"
    
    environment:
      - ARKIME_URL=${ARKIME_URL:-https://localhost:8005}
      - ARKIME_USERNAME=${ARKIME_USERNAME}
      - ARKIME_PASSWORD=${ARKIME_PASSWORD}
      - ARKIME_VERIFY_SSL=${ARKIME_VERIFY_SSL:-false}
    
    volumes:
      - /sec/ai-detector/output/anomaly_logs:/sec/ai-detector/output/anomaly_logs:ro
      - /sec/ai-middle/logs:/sec/ai-middle/logs
      - ./.env:/app/.env:ro

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.0.2
    user: root
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /sec/ai-middle/logs:/usr/share/filebeat/logs:ro
      - /sec/ai-middle/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    environment:
      - ELASTICSEARCH_HOSTS=https://localhost:9200
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}